### ISSUE TITLE
[:vspace](1ex) may produce empty `<p></p>`

### ISSUE THREAD

**Issue by kno10** [decker-edu/decker#101]
To increase spacing (for semantic reasons), I sometimes insert vspace:
```markdown
Text:

- bullets

[:vspace](1ex)

Text:

- bullets
```
However, this renders into
```html
<p>Text:</p>
<ul>...</ul>
<p></p>
<div style="display:block; clear:both; height:1ex;"></div>
<p></p>
<p>Text:</p>
<ul>...</ul>
```

Removing the newlines around the vspace make the subsequent text not be a paragraph at all. Putting just the HTML instead of the vspace macro works as desired.

**Comment by monofon** [comment]
Hm, the browser seems to hallucinate these empty `<p></p>` tags. The generated HTML looks like this:

```html
<p>Line 1</p>
<p><div style="display:block; clear:both; height:10em;"></div></p>
<p>Line 2</p>
```

The reason might be, that `<p><div></div></p>` is not exactly legal HTML. The browser seems to know that.

Decker processes macros in an Inline context and generates a `RawInline` element. The Pandoc writer seems to automatically wrap this in a `<p>` element because it is surrounded by empty lines.

**Comment by monofon** [comment]
Using a `<span>` here helps.
