### ISSUE TITLE
Mermaid support deprecated?

### ISSUE THREAD

**Issue by marcerich** [decker-edu/decker#126]
In the rendered-code-deck.md test deck we still have one slide specifying support for mermaid figures. However, this slide seems to be deprecated for quit some time, e.g., it comments-out the actual code and also used the old `.columns` syntax we apparently don't support anymore. The latter one is now updated so one sees at least the code block with an error. Anyway, did we want to disfunc mermaid support completely? Is it superset now by plantUML?

**Comment by monofon** [comment]
Deprecated? Not that I would know. 

You need to have `mermaid-cli` to be installed, of course.

No idea, why the test was commented out. 

<img width="861" alt="Bildschirmfoto 2024-10-10 um 09 40 06" src="https://github.com/user-attachments/assets/53f59e3d-3b98-4b31-94e0-3a1a731bb1d2">

`.columns` is just a shortcut for `layout="columns"` and works. I use it all the time because it is shorter.

**Comment by marcerich** [comment]
Ok thanks. Since it was commented out it seemed deprecated. I included it again. About `.columns`, it did not render two columns in the current development branch. However it did when I changed it to `layout=columns`
