### ISSUE TITLE
custom dialog broken

### ISSUE THREAD

**Issue by mbotsch** [decker-edu/decker#14]
The custom dialog that is showing when pressing `r` and a recording is present is broken
<img width="785" alt="Screenshot 2022-10-24 at 22 04 32" src="https://user-images.githubusercontent.com/31275467/197618564-0860a6f4-9d03-4b5d-bd69-a8393d01b610.png">

**Comment by salbeira** [comment]
Urgh that looks ugly! I did not write that 😇 
But git blame still tags be because of that gitlab web-editor commit that set the whole file to "changed by me". Urhg. Anyway.

Check out branch fix-dialog-html to check it out. The dialog title content was set to HTML "Text" instead of setting the dialog content to an Element.
