### ISSUE TITLE
Limit zoom in zoom plugin to 2x or 3x

### ISSUE THREAD

**Issue by kno10** [decker-edu/decker#91]
The decker zoom plugin (as opposed to the reveal.js zoom plugin) does not have a maximum zoom level.

It happens to me a lot that I click on a small equation, and then reveal.js zooms in way too much (e.g., if you end up clicking on a single math $x$). I have disabled the zoom plugin because of this behaviour - it fails me more often than I use it.

I suggest to add a configuration option to set a maximum zoom (e.g., 2 or 3), configurable.

**Comment by salbeira** [comment]
I also often see people presenting rapidly double clicking on anything they are currently focusing on. Short pieces of text can quickly turn into a fest of zoom ins and outs. This also always selects text which can turn into quite the visual overload.

Maybe we should add a few things to this:

- Disable user-select on all (or certain?) elements when in presenter mode so text stops getting selected when double clicked on.
- Add a "ping" to elements double clicked on in presenter mode so the user knows what they double clicked on, even if no zoom happened because the clicked element was too large to begin with.
- Add the option to have the zoomed to element be outlined so they know what was zoomed to.

These are things I played around with a bit to see what can be done with the current zoom-plugin.

Config options would be:

```
zoom:
    max: number
    outline: string -> e.g. '2px solid var(--foreground-color)'
    ping: true | false
```

omitting any values should keep current behaviour.

**Comment by kno10** [comment]
Ctrl-Click / Alt-Click is the behavior of the standard reveal.js zoom plugin, with a fixed zoom factor, default value 2.
I have not yet tried it, whether this behavior suits me better.

**Comment by mbotsch** [comment]
I added two config options to the zoom plugin, to be defined in decker.yaml or default.yaml:
```
zoom:
    max: <number>
    trigger: "doubleClick" | "tripleClick" | "altClick" 
```
The default is `max=100` and `trigger=doubleClick`.
